/* Study Desk Editorial certificate: shareable, printable and privacy-conscious with no personal identity required. */
import { useState } from "react";
import { ArrowLeft, Check, Copy, Download, Share2, Sparkles } from "lucide-react";
import { trackLearningEvent } from "@/lib/analytics";

const labels: Record<string, string> = { "prompt-detective": "Prompt Detective", "fact-check-quest": "Fact Check Quest", "ai-safety-lab": "AI Safety Lab" };
const lessons: Record<string, string> = { "prompt-detective": "better prompting", "fact-check-quest": "evidence-led thinking", "ai-safety-lab": "responsible AI habits" };
export default function CertificatePage() {
  const params = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const game = params.get("game") || "prompt-detective"; const score = Number(params.get("score") || 0); const total = Number(params.get("total") || 5); const label = labels[game] || labels["prompt-detective"]; const [copied, setCopied] = useState(false);
  const shareUrl = typeof window !== "undefined" ? window.location.href : "";
  const share = async () => { trackLearningEvent("certificate_share", { game, score, total }); if (navigator.share) { await navigator.share({ title: `${label} — AI for Students`, text: `I completed ${label} on AI for Students with a score of ${score}/${total}.`, url: shareUrl }); } else { await navigator.clipboard?.writeText(shareUrl); setCopied(true); } };
  return <div className="certificate-page"><header className="progress-header"><a className="game-brand" href="/"><span className="progress-logo">✦</span><span><strong>AI</strong> for <em>Students</em></span></a><a className="game-return" href="/progress"><ArrowLeft size={15} /> Your progress</a></header><main className="certificate-main"><div className="certificate-paper"><div className="certificate-topline"><span>AI FOR STUDENTS</span><span>FIELD NOTE / {new Date().getFullYear()}</span></div><div className="certificate-mark"><Sparkles size={22} /></div><span className="game-kicker">LEARNING MILESTONE</span><h1>Well investigated.</h1><p className="certificate-intro">You completed the <strong>{label}</strong> learning game and practiced {lessons[game] || "a useful AI skill"}.</p><div className="certificate-score"><strong>{score}<small> / {total}</small></strong><span>verified decisions</span></div><div className="certificate-signature"><span>Keep the thinking</span><span>AI for Students</span></div><div className="certificate-id">A private, shareable record generated in your browser. No account or personal data required.</div></div><div className="certificate-actions"><button className="game-button game-button--primary" onClick={() => { trackLearningEvent("certificate_print", { game, score, total }); window.print(); }}><Download size={16} /> Print / save PDF</button><button className="game-button game-button--quiet" onClick={share}><Share2 size={16} /> {copied ? "Link copied" : "Share certificate"}</button><a className="text-link" href="/progress"><Check size={15} /> Back to progress</a></div><p className="certificate-note">This certificate celebrates practice, not perfection. Keep verifying, asking better questions and protecting your own work.</p></main></div>;
}
