import { ArrowLeft, ArrowRight, BookOpen, LockKeyhole, Search, SearchCheck, Sparkles } from "lucide-react";
import PromptDetective from "@/components/game/PromptDetective";
import FactCheckQuest from "@/components/game/FactCheckQuest";
import AISafetyLab from "@/components/game/AISafetyLab";
import InteractiveLab from "@/components/game/InteractiveLab";
import AuthControls from "@/components/AuthControls";

const markImage = "/manus-storage/ai-students-mark_e5155fd0.png";

export default function GamePage() {
  const gameParam = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("game") : null;
  const isFact = gameParam === "fact";
  const isSafety = gameParam === "safety";
  const isWorkshop = gameParam === "workshop";
  const isSourceHunt = gameParam === "source-hunt";
  const title = isSafety ? <>AI Safety<br /><em>Lab</em></> : isFact ? <>Fact<br /><em>Check Quest</em></> : isWorkshop ? <>Prompt<br /><em>Workshop</em></> : isSourceHunt ? <>Source<br /><em>Hunt</em></> : <>Prompt<br /><em>Detective</em></>;
  const description = isSafety ? "Pause before you share. Keep a human in the loop." : isFact ? "Follow the claim. Find the evidence. Keep your confidence calibrated." : isWorkshop ? "Assemble a useful AI brief by building the workflow block by block." : isSourceHunt ? "Sequence an evidence check before a claim travels." : "Read the brief. Spot the stronger request. Keep the thinking.";
  return <div className="game-page"><header className="game-header"><a className="game-brand" href="/"><img src={markImage} alt="" /><span><strong>AI</strong> for <em>Students</em></span></a><a className="game-return" href="/"><ArrowLeft size={15} /> Back to the desk</a><AuthControls /></header><main className="game-main"><div className="game-intro"><div><div className="game-intro-top"><span className="game-kicker">LEARNING MATERIAL / PLAY TO LEARN</span></div><h1>{title}</h1></div><div><span className="game-resource"><BookOpen size={14} /> {isWorkshop || isSourceHunt ? "hands-on lab" : "15-case lesson"}</span><p>{description}</p></div></div><nav className="game-switcher" aria-label="Learning games"><a className={!isFact && !isSafety && !isWorkshop && !isSourceHunt ? "is-current" : ""} href="/play"><Sparkles size={15} /><span><strong>Prompt Detective</strong><small>Build better requests</small></span><ArrowRight size={14} /></a><a className={isFact ? "is-current" : ""} href="/play?game=fact"><SearchCheck size={15} /><span><strong>Fact Check Quest</strong><small>Verify before you trust</small></span><ArrowRight size={14} /></a><a className={isSafety ? "is-current" : ""} href="/play?game=safety"><LockKeyhole size={15} /><span><strong>AI Safety Lab</strong><small>Make the safer move</small></span><ArrowRight size={14} /></a><a className={isWorkshop ? "is-current" : ""} href="/play?game=workshop"><Sparkles size={15} /><span><strong>Prompt Workshop</strong><small>Build, don't guess</small></span><ArrowRight size={14} /></a><a className={isSourceHunt ? "is-current" : ""} href="/play?game=source-hunt"><Search size={15} /><span><strong>Source Hunt</strong><small>Sequence the check</small></span><ArrowRight size={14} /></a></nav><div className="game-board"><div className="game-board-tab">{isSafety ? "FIELD GAME 03" : isFact ? "FIELD GAME 02" : isWorkshop ? "HANDS-ON LAB 04" : isSourceHunt ? "HANDS-ON LAB 05" : "FIELD GAME 01"} <span>✦</span></div>{(isFact || isSafety) && <img className="game-art-note" src={isSafety ? "/manus-storage/ai-safety-lab-note_1dffd5e2.png" : "/manus-storage/fact-check-quest-board_f72aa636.png"} alt={isSafety ? "Illustrated safety note with a lock and shield" : "Illustrated evidence board with source cards and a magnifying glass"} />}{isSafety ? <AISafetyLab /> : isFact ? <FactCheckQuest /> : isWorkshop ? <InteractiveLab mode="workshop" /> : isSourceHunt ? <InteractiveLab mode="source-hunt" /> : <PromptDetective />}</div></main><footer className="game-page-footer"><span>AI for Students</span><span>Learn the tool. Keep the thinking.</span></footer></div>;
}
