import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Search, Sparkles } from "lucide-react";
import AuthControls from "@/components/AuthControls";
import { curriculumTopics, topicTracks } from "@/data/curriculumTopics";

export default function TopicsPage() {
  const [query, setQuery] = useState(""); const [track, setTrack] = useState("all");
  const visible = useMemo(() => curriculumTopics.filter((topic) => (track === "all" || topic.track === track) && topic.title.toLowerCase().includes(query.toLowerCase())), [query, track]);
  return <div className="topics-page"><header className="game-header"><a className="game-brand" href="/"><span className="progress-logo">✦</span><span><strong>AI</strong> for <em>Students</em></span></a><a className="game-return" href="/"><ArrowLeft size={15} /> Back to the desk</a><AuthControls /></header><main className="topics-main"><div className="topics-hero"><span className="game-kicker">THE CURRICULUM / 120 FIELD NOTES</span><h1>Find a useful<br /><em>next step.</em></h1><p>Explore AI topics by track, then practice the idea inside a game, guide or hands-on lab.</p><div className="topics-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a topic..." aria-label="Search curriculum topics" /></div></div><div className="topic-filters"><button className={track === "all" ? "is-active" : ""} onClick={() => setTrack("all")}>All topics</button>{topicTracks.map((item) => <button key={item.id} className={track === item.id ? "is-active" : ""} onClick={() => setTrack(item.id)}>{item.label}</button>)}</div><div className="topics-count"><span>{visible.length} topics</span><span>Start small. Keep the thinking.</span></div><div className="topic-grid">{visible.map((topic, index) => <a className="topic-card" href={topic.game === "prompt-detective" ? "/play" : topic.game === "fact-check-quest" ? "/play?game=fact" : "/play?game=safety"} key={topic.id}><span className="topic-number">{String(index + 1).padStart(2, "0")}</span><div><strong>{topic.title}</strong><small>{topicTracks.find((item) => item.id === topic.track)?.label} · {topic.level}</small></div><ArrowRight size={15} /></a>)}</div>{visible.length === 0 && <div className="topics-empty"><Sparkles size={18} /><p>No topic matched that search. Try “privacy”, “CV” or “prompt”.</p></div>}</main><footer className="game-page-footer"><span>AI for Students</span><span>Learn the tool. Keep the thinking.</span></footer></div>;
}
