/* Study Desk Editorial game: safety scenarios are practical, non-alarmist and action-oriented. */
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, LockKeyhole, RotateCcw, ShieldCheck, Sparkles, X } from "lucide-react";
import { toast } from "sonner";
import { completeGame, startGame } from "@/lib/learningProgress";
import { trackLearningEvent } from "@/lib/analytics";
import PostGameFeedback from "@/components/game/PostGameFeedback";

type SafetyQuestion = { scenario: string; choices: { id: string; text: string; correct: boolean; explanation: string }[] };
const questions: SafetyQuestion[] = [
  { scenario: "A study tool asks you to paste your full name, phone number and private class document to summarize it. What is the safer move?", choices: [
    { id: "a", text: "Paste everything because the tool promises it will be quick.", correct: false, explanation: "Speed does not make sensitive information safe. Remove identifiers and use only what the task requires." },
    { id: "b", text: "Remove personal details, check the tool’s data policy and use a local or trusted option when possible.", correct: true, explanation: "Data minimization is a strong safety habit: share less, understand the policy and choose a trusted workflow." },
    { id: "c", text: "Upload the document but change the file name.", correct: false, explanation: "A new file name does not remove private content inside the document." },
  ]},
  { scenario: "Your course says submitted work must be your own. How can AI support you responsibly?", choices: [
    { id: "a", text: "Ask AI to write the whole submission in your voice.", correct: false, explanation: "A generated submission can break course rules and prevents you from demonstrating your own learning." },
    { id: "b", text: "Use it to ask questions, practice, outline ideas or give feedback, then follow the course policy and disclose use if required.", correct: true, explanation: "Responsible use respects the assessment rule and keeps the learner’s thinking and final work in control." },
    { id: "c", text: "Use AI secretly as long as you edit a few sentences.", correct: false, explanation: "Editing does not automatically make outsourced work acceptable. The policy and your actual contribution matter." },
  ]},
  { scenario: "An AI answer gives medical, legal or financial advice with no sources. What should you do?", choices: [
    { id: "a", text: "Follow it if the writing sounds confident.", correct: false, explanation: "Fluent wording is not proof. High-stakes decisions need qualified, current and context-specific guidance." },
    { id: "b", text: "Treat it as a starting point, verify with authoritative sources and consult a qualified professional for your situation.", correct: true, explanation: "AI can help you form questions, but high-stakes decisions require independent verification and appropriate human expertise." },
    { id: "c", text: "Ask the same AI to rate its own certainty and accept the score.", correct: false, explanation: "Self-rated confidence is not an independent safety check." },
  ]},
  { scenario: "You notice an AI-generated image falsely presents a classmate in a harmful situation. What is the best response?", choices: [
    { id: "a", text: "Share it privately so more people can decide whether it is real.", correct: false, explanation: "Sharing harmful material spreads the damage even when framed as a question." },
    { id: "b", text: "Do not amplify it, preserve only what is needed for reporting and use the school/platform reporting route.", correct: true, explanation: "Pause the spread, protect the person’s privacy and use an appropriate reporting process." },
    { id: "c", text: "Make a similar image of the creator to teach them a lesson.", correct: false, explanation: "Retaliation creates more harm and does not solve the safety issue." },
  ]},
];
const KEY = "ai-students-safety-best";

export default function AISafetyLab() {
  const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [best, setBest] = useState(() => Number(typeof window === "undefined" ? 0 : window.localStorage.getItem(KEY) || 0));
  useEffect(() => { if (typeof window !== "undefined" && new URLSearchParams(window.location.search).has("demo")) { setStarted(true); startGame("ai-safety-lab"); } }, []);
  const start = () => { setStarted(true); setIndex(0); setScore(0); setSelected(null); startGame("ai-safety-lab"); trackLearningEvent("learning_game_start", { game: "ai-safety-lab" }); };
  const choose = (id: string) => { if (selected) return; setSelected(id); const choice = questions[index].choices.find((item) => item.id === id); trackLearningEvent("learning_game_answer", { game: "ai-safety-lab", question: index + 1, correct: Boolean(choice?.correct) }); if (choice?.correct) { setScore((value) => value + 1); toast.success("Safe choice. Read the action note."); } };
  const next = () => { if (!selected) return; if (index === questions.length - 1) { const finalScore = score; completeGame("ai-safety-lab", finalScore); trackLearningEvent("learning_game_complete", { game: "ai-safety-lab", score: finalScore, total: questions.length }); if (finalScore > best) { setBest(finalScore); window.localStorage.setItem(KEY, String(finalScore)); } setIndex(questions.length); return; } setIndex((value) => value + 1); setSelected(null); };
  const restart = () => { setStarted(false); setIndex(0); setScore(0); setSelected(null); };
  if (!started) return <div className="game-picker"><div className="game-picker-heading"><span className="game-kicker">AI SAFETY LAB / FIELD GAME 03</span><h2>Make the<br /><em>safer move.</em></h2><p>Four scenarios for privacy, academic integrity, high-stakes information and digital harm.</p></div><div className="fact-preview safety-preview"><span className="fact-preview-icon"><LockKeyhole size={24} /></span><div><strong>What you will practice</strong><p>Pause before sharing, check the rules and keep a human in the loop when the stakes are high.</p></div></div><button className="game-button game-button--primary fact-start" onClick={start}><ShieldCheck size={16} /> Open the first case <ArrowRight size={16} /></button>{best > 0 && <div className="best-score"><Sparkles size={15} /> Best safety score: <strong>{best}/{questions.length}</strong></div>}</div>;
  if (index >= questions.length) return <div className="game-result"><div className="result-mark badge-burst"><ShieldCheck size={26} /></div><span className="game-kicker">SAFETY CHECK COMPLETE</span><h2>{score}<small> / {questions.length}</small></h2><p className="result-message">{score >= 3 ? "You are building the pause that protects people and your own work." : "Safety is a habit, not a one-time test. Replay the cases and read each action note."}</p><div className="result-note"><strong>Your next move</strong><span>Before using any AI tool, ask: what data am I sharing, what rule applies and what should a human verify?</span></div><PostGameFeedback game="ai-safety-lab" /><div className="game-result-actions"><button className="game-button game-button--primary" onClick={() => { setIndex(0); setScore(0); setSelected(null); startGame("ai-safety-lab"); }}><RotateCcw size={16} /> Play again</button><button className="game-button game-button--quiet" onClick={restart}>Choose another game</button><a className="game-button game-button--quiet" href={`/certificate?game=ai-safety-lab&score=${score}&total=${questions.length}`}>Share certificate <ArrowRight size={15} /></a></div></div>;
  const current = questions[index]; const chosen = current.choices.find((choice) => choice.id === selected);
  return <div className="game-play"><div className="game-progress-row"><span>CASE {String(index + 1).padStart(2, "0")} / 04</span><span>{score} safe choices</span></div><div className="game-progress"><span style={{ width: `${((index + (selected ? 1 : 0)) / questions.length) * 100}%` }} /></div><div className="fact-claim safety-claim"><span className="game-kicker">SAFETY CARD / PAUSE & CHECK</span><blockquote>{current.scenario}</blockquote></div><div className="answer-list">{current.choices.map((choice, choiceIndex) => <button key={choice.id} className={`answer-card ${selected === choice.id ? "is-selected" : ""} ${selected && choice.correct ? "is-correct" : ""} ${selected === choice.id && !choice.correct ? "is-wrong" : ""}`} disabled={Boolean(selected)} onClick={() => choose(choice.id)}><span className="answer-letter">{String.fromCharCode(65 + choiceIndex)}</span><span>{choice.text}</span>{selected && choice.correct && <Check className="answer-status" size={17} />}{selected === choice.id && !choice.correct && <X className="answer-status" size={17} />}</button>)}</div>{selected && <div className={`game-feedback ${chosen?.correct ? "game-feedback--good" : "game-feedback--learn"}`}><div className="feedback-icon">{chosen?.correct ? <Check size={17} /> : <Sparkles size={17} />}</div><div><strong>{chosen?.correct ? "That protects the person and the process." : "Pause before you pass it on."}</strong><p>{chosen?.explanation}</p></div></div>}<div className="game-footer-actions"><a className="game-back" href="/play"><ArrowLeft size={15} /> Learning games</a><button className="game-button game-button--primary" onClick={next} disabled={!selected}>{index === questions.length - 1 ? "See your result" : "Next case"} <ArrowRight size={16} /></button></div></div>;
}
