/* Study Desk Editorial game: evidence cards, source quality signals, calm feedback and practical verification habits. */
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, RotateCcw, SearchCheck, Sparkles, X } from "lucide-react";
import { reviewedMeta } from "@/data/contentSchema";
import { toast } from "sonner";
import { completeGame, startGame } from "@/lib/learningProgress";
import { trackLearningEvent } from "@/lib/analytics";
import { orderChoices } from "@/lib/answerOrder";
import PostGameFeedback from "@/components/game/PostGameFeedback";
import ShareResult from "@/components/game/ShareResult";

type FactQuestion = { claim: string; context: string; choices: { id: string; text: string; correct: boolean; explanation: string }[] };

const factQuestionBank: FactQuestion[] = [
  { claim: "“AI always gives better answers when you write a longer prompt.”", context: "You see this sentence in a social media post. What is your best next move?", choices: [
    { id: "a", text: "Share it because it sounds like useful advice.", correct: false, explanation: "The claim is too absolute. Prompt quality depends on the task and relevant context, not simply length." },
    { id: "b", text: "Ask what evidence supports ‘always’, then test the advice on a few different tasks.", correct: true, explanation: "Strong fact-checking questions absolute language and checks whether a claim holds across examples." },
    { id: "c", text: "Ask another chatbot if the post is true and trust its yes/no answer.", correct: false, explanation: "A second AI opinion is not independent evidence. You need observable tests or reliable sources." },
  ]},
  { claim: "A search result’s first link is the most reliable source.", context: "You need one fact for a class note. Which approach is strongest?", choices: [
    { id: "a", text: "Use the first result and do not spend time comparing it.", correct: false, explanation: "Search ranking is not the same as authority. The first result may be commercial, outdated or unsourced." },
    { id: "b", text: "Compare a primary source or institution with at least one independent reliable source.", correct: true, explanation: "Source quality and agreement matter. Triangulation helps you catch missing context and errors." },
    { id: "c", text: "Pick the page with the most confident headline.", correct: false, explanation: "Confident wording is not evidence of accuracy. Inspect who published the claim and what supports it." },
  ]},
  { claim: "“This graph proves that the new policy caused the change.”", context: "A chart shows two trends rising at the same time. What should you notice?", choices: [
    { id: "a", text: "A rising line proves that one caused the other.", correct: false, explanation: "Two trends can move together without one causing the other. Other explanations and time windows matter." },
    { id: "b", text: "Check the axes, time period, sample, missing data and whether the source supports a causal conclusion.", correct: true, explanation: "Reading a graph critically means checking how it was made before accepting its interpretation." },
    { id: "c", text: "Ignore the graph because charts are always biased.", correct: false, explanation: "A chart needs scrutiny, not automatic rejection. Its method and source determine how useful it is." },
  ]},
  { claim: "An AI-generated citation is safe to use if it has a realistic title.", context: "AI suggests a paper for your research. What is the responsible action?", choices: [
    { id: "a", text: "Copy it into the bibliography because the title looks academic.", correct: false, explanation: "AI can invent realistic-looking citations. A title alone does not prove that the source exists." },
    { id: "b", text: "Locate the original paper through a library or publisher, then check author, date and claim.", correct: true, explanation: "Verification means finding the original record and checking that it actually supports what you plan to say." },
    { id: "c", text: "Ask the AI to add a DOI so the citation looks complete.", correct: false, explanation: "Adding more details does not verify them. Every citation field must be checked against an original record." },
  ]},
  { claim: "A government-looking website is automatically current and unbiased.", context: "You find an official-looking page for a research note. What should you inspect?", choices: [{ id: "a", text: "The author, publication date, evidence and purpose of the page.", correct: true, explanation: "Authority helps, but currency, evidence and purpose still matter." }, { id: "b", text: "Only the logo.", correct: false, explanation: "Visual identity is not evidence of currency or quality." }, { id: "c", text: "The page length.", correct: false, explanation: "Long pages can still be outdated or unsupported." }] },
  { claim: "If three websites repeat a claim, it has been independently verified.", context: "You are comparing search results. What is the key question?", choices: [{ id: "a", text: "Whether they all copied the same original claim.", correct: true, explanation: "Repetition is not independence; trace the claim back to its source." }, { id: "b", text: "Which page has the largest font.", correct: false, explanation: "Design does not establish independence." }, { id: "c", text: "Whether the headline is dramatic.", correct: false, explanation: "Dramatic wording can increase attention without increasing evidence." }] },
  { claim: "A small sample can prove a result applies to everyone.", context: "An AI summarizes a survey of 12 people. What should you do?", choices: [{ id: "a", text: "Treat the sample size and selection limits as part of the conclusion.", correct: true, explanation: "A small or selective sample limits how widely a result can be generalized." }, { id: "b", text: "Replace the sample size with a larger estimate.", correct: false, explanation: "Changing the data destroys the evidence trail." }, { id: "c", text: "Ignore the methods section.", correct: false, explanation: "Methods explain what the sample can support." }] },
  { claim: "A percentage change is meaningful without knowing the baseline.", context: "A report says sign-ups increased by 50%. What is missing?", choices: [{ id: "a", text: "The starting value, time period and calculation.", correct: true, explanation: "Relative changes need a baseline and timeframe to be interpreted." }, { id: "b", text: "A more exciting adjective.", correct: false, explanation: "Language cannot replace the missing numbers." }, { id: "c", text: "The font used in the report.", correct: false, explanation: "Typography does not define the size of a change." }] },
  { claim: "A chart with a truncated axis can make a small difference look large.", context: "Two bars look dramatically different. What should you inspect first?", choices: [{ id: "a", text: "The axis scale, labels, units and full range.", correct: true, explanation: "Axis choices can change the visual impression without changing the data." }, { id: "b", text: "Only the color palette.", correct: false, explanation: "Color matters for accessibility, but scale is central to interpretation." }, { id: "c", text: "The number of animations.", correct: false, explanation: "Animation does not validate the underlying chart." }] },
  { claim: "A quote is reliable if it is widely shared online.", context: "You see a famous quote attributed to a scientist. What should you check?", choices: [{ id: "a", text: "The original speech, publication or archival record.", correct: true, explanation: "Attribution should be checked against a primary record where possible." }, { id: "b", text: "The number of reposts.", correct: false, explanation: "Popularity is not evidence of authorship." }, { id: "c", text: "Whether it fits your argument.", correct: false, explanation: "A convenient quote can still be misattributed." }] },
  { claim: "An AI summary preserves every important caveat by default.", context: "You are using a summary to plan further reading. What should you do?", choices: [{ id: "a", text: "Compare the summary with the original sections containing limitations.", correct: true, explanation: "Summaries can compress or omit conditions, so inspect the source." }, { id: "b", text: "Assume caveats are too technical to matter.", correct: false, explanation: "Limitations often change what a claim means." }, { id: "c", text: "Use the shortest summary available.", correct: false, explanation: "Shortness does not guarantee completeness." }] },
  { claim: "A source is objective because it says it is objective.", context: "A product page describes its own research as unbiased. What is the next step?", choices: [{ id: "a", text: "Check methods, funding, incentives and independent evidence.", correct: true, explanation: "Claims about neutrality need support and context." }, { id: "b", text: "Accept the label immediately.", correct: false, explanation: "Self-description is not independent evaluation." }, { id: "c", text: "Reject all research from companies.", correct: false, explanation: "Funding context matters, but it does not automatically settle quality." }] },
  { claim: "A confident AI answer is evidence that uncertainty is low.", context: "The model gives no sources but uses precise language. What should you infer?", choices: [{ id: "a", text: "Nothing about accuracy; request evidence and verify important claims.", correct: true, explanation: "Fluency and confidence are not reliable measures of truth." }, { id: "b", text: "The answer is probably correct.", correct: false, explanation: "Plausibility is not verification." }, { id: "c", text: "The model must have searched live sources.", correct: false, explanation: "You cannot infer tool use from writing style." }] },
  { claim: "A search snippet contains enough context for a complex claim.", context: "You need to cite a nuanced finding. What should you open?", choices: [{ id: "a", text: "The full original source and the relevant passage.", correct: true, explanation: "Snippets are abbreviated and can omit qualifications." }, { id: "b", text: "Only the snippet text.", correct: false, explanation: "A snippet may not represent the source accurately." }, { id: "c", text: "A screenshot without the URL.", correct: false, explanation: "Without the source, the claim cannot be traced." }] },
  { claim: "A source is reliable because it agrees with your existing opinion.", context: "You find evidence that supports your argument. What should you do?", choices: [{ id: "a", text: "Check its methods and seek credible evidence that could challenge the claim.", correct: true, explanation: "Good research tests evidence rather than selecting only what feels agreeable." }, { id: "b", text: "Stop searching immediately.", correct: false, explanation: "Stopping at confirmation can hide important context." }, { id: "c", text: "Remove the source date.", correct: false, explanation: "Date context is part of responsible evaluation." }] },
  { claim: "A single dramatic example proves a broad trend.", context: "A post shows one unusual case. What should you ask for?", choices: [{ id: "a", text: "A representative dataset and comparison group.", correct: true, explanation: "One case can illustrate a possibility but not establish a trend." }, { id: "b", text: "More dramatic wording.", correct: false, explanation: "Rhetoric does not increase representativeness." }, { id: "c", text: "A larger image.", correct: false, explanation: "Presentation cannot replace a comparison." }] },
  { claim: "A study found an association, so one factor caused the other.", context: "You are summarizing a correlation. What should you write?", choices: [{ id: "a", text: "Describe the association and avoid claiming causation without stronger evidence.", correct: true, explanation: "Correlation alone does not establish which factor caused what." }, { id: "b", text: "Use caused because it is shorter.", correct: false, explanation: "Short language can still change the claim." }, { id: "c", text: "Delete the sample details.", correct: false, explanation: "Sample details help readers judge scope." }] },
  { claim: "A source is current because its webpage looks modern.", context: "A changing policy is being cited. What matters?", choices: [{ id: "a", text: "The publication or update date and the official current version.", correct: true, explanation: "Design does not establish freshness." }, { id: "b", text: "The page's color scheme.", correct: false, explanation: "Visual design says nothing about date." }, { id: "c", text: "The number of comments.", correct: false, explanation: "Comments do not establish the current rule." }] },
  { claim: "A source with a long bibliography must support your exact sentence.", context: "A paper is cited for a specific claim. What should you inspect?", choices: [{ id: "a", text: "The relevant passage and whether its method supports that sentence.", correct: true, explanation: "Many references do not guarantee support for one particular claim." }, { id: "b", text: "Only the reference count.", correct: false, explanation: "Quantity is not relevance." }, { id: "c", text: "The abstract title alone.", correct: false, explanation: "The title cannot show the precise evidence." }] },
  { claim: "A screenshot of a dashboard is enough to reproduce a result.", context: "You want to audit a reported number. What is missing?", choices: [{ id: "a", text: "The dataset, definitions, filters and date of extraction.", correct: true, explanation: "Reproducibility needs the inputs and choices behind the view." }, { id: "b", text: "A brighter screenshot.", correct: false, explanation: "Image quality does not reveal hidden filters." }, { id: "c", text: "A more confident caption.", correct: false, explanation: "Caption tone is not methodology." }] },
  { claim: "An expert's title makes every claim they post reliable.", context: "You are evaluating a social-media thread. What should you do?", choices: [{ id: "a", text: "Check the specific claim, evidence and relevant expertise.", correct: true, explanation: "Authority is contextual and still needs evidence." }, { id: "b", text: "Accept every sentence.", correct: false, explanation: "Expertise does not make every statement automatically correct." }, { id: "c", text: "Ignore all credentials.", correct: false, explanation: "Credentials can be context, just not proof alone." }] },
  { claim: "A chart's total can be compared even when categories overlap.", context: "A report adds several categories to a total. What should you check?", choices: [{ id: "a", text: "Whether categories are mutually exclusive or double-count people.", correct: true, explanation: "Overlapping categories can make totals look larger than the population." }, { id: "b", text: "The chart's font.", correct: false, explanation: "Typography does not resolve overlap." }, { id: "c", text: "The number of colors.", correct: false, explanation: "Color does not define category membership." }] },
  { claim: "If an image has no obvious edits, its context is proven.", context: "A photo is being used to support a claim. What should you verify?", choices: [{ id: "a", text: "Where, when and why the image was originally published.", correct: true, explanation: "Authenticity and context are separate questions." }, { id: "b", text: "Only its resolution.", correct: false, explanation: "Resolution cannot establish context." }, { id: "c", text: "Whether it matches your belief.", correct: false, explanation: "Agreement is not verification." }] },
  { claim: "A model's cited URL proves it read the page.", context: "An AI answer includes a link. What should you do?", choices: [{ id: "a", text: "Open the source and confirm the cited passage supports the claim.", correct: true, explanation: "A URL can be irrelevant, broken or misrepresented." }, { id: "b", text: "Trust the link label.", correct: false, explanation: "Labels can be generated or misleading." }, { id: "c", text: "Count the links.", correct: false, explanation: "More links do not guarantee support." }] },
  { claim: "A poll result applies to everyone who did not answer it.", context: "A voluntary online poll reports a strong result. What is the key caution?", choices: [{ id: "a", text: "Respondents may differ from the wider population.", correct: true, explanation: "Voluntary responses can introduce selection bias." }, { id: "b", text: "The result is automatically universal.", correct: false, explanation: "Participation was not random by default." }, { id: "c", text: "The poll needs more emojis.", correct: false, explanation: "Presentation cannot fix sampling." }] },
  { claim: "A claim becomes stronger when repeated by many accounts.", context: "You see the same statistic everywhere. What matters?", choices: [{ id: "a", text: "Whether the repetitions trace back to independent, credible evidence.", correct: true, explanation: "Many copies can originate from one unsupported post." }, { id: "b", text: "The number of reposts alone.", correct: false, explanation: "Popularity is not independence." }, { id: "c", text: "The oldest screenshot.", correct: false, explanation: "Age does not establish accuracy." }] },
  { claim: "A negative result means the tested idea is impossible.", context: "A small study found no statistically clear effect. What is fair?", choices: [{ id: "a", text: "Describe what the study could detect and avoid overgeneralizing.", correct: true, explanation: "Study size and design affect what a negative result can rule out." }, { id: "b", text: "Declare the idea impossible.", correct: false, explanation: "No detected effect is not always proof of no effect." }, { id: "c", text: "Hide the uncertainty.", correct: false, explanation: "Uncertainty is part of the result." }] },
  { claim: "A translated quote has exactly the same nuance as the original.", context: "You are citing a translated interview. What should you check?", choices: [{ id: "a", text: "The original wording, translator and any meaningful ambiguity.", correct: true, explanation: "Translation can change nuance and should be transparent." }, { id: "b", text: "Only the quote's popularity.", correct: false, explanation: "Popularity cannot validate a translation." }, { id: "c", text: "Remove the language information.", correct: false, explanation: "Language context helps readers evaluate the quote." }] },
  { claim: "A prediction that came true proves the method always works.", context: "One forecast matched reality. What should you ask?", choices: [{ id: "a", text: "How many forecasts were made and how they were evaluated.", correct: true, explanation: "A single hit can be selected from many misses." }, { id: "b", text: "Whether the forecast sounds impressive.", correct: false, explanation: "Impression is not evaluation." }, { id: "c", text: "Whether misses were deleted.", correct: false, explanation: "Deleting misses would hide important evidence." }] },
  { claim: "A study's conclusion applies to every population because the sample was large.", context: "A large study used one narrow group. What should you check?", choices: [{ id: "a", text: "Whether the sample matches the population in the claim and how the study was designed.", correct: true, explanation: "Large size does not remove limits in representativeness or generalization." }, { id: "b", text: "Assume the size settles the question.", correct: false, explanation: "Sample size is only one part of evidence quality." }, { id: "c", text: "Ignore the participant details.", correct: false, explanation: "Participant details define the study's scope." }] },
  ];

export const factQuestions = factQuestionBank.map((item, index) => ({ ...item, ...reviewedMeta("fact-check-quest", index, item.claim, ["evidence", "research"]) }));

const STORAGE_KEY = "ai-students-fact-check-best";

export default function FactCheckQuest() {
  const [started, setStarted] = useState(false);
  const [index, setIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [best, setBest] = useState(() => Number(typeof window === "undefined" ? 0 : window.localStorage.getItem(STORAGE_KEY) || 0));
  useEffect(() => { if (typeof window !== "undefined" && new URLSearchParams(window.location.search).has("demo")) { setStarted(true); startGame("fact-check-quest"); } }, []);
  const start = () => { setStarted(true); setIndex(0); setScore(0); setSelected(null); startGame("fact-check-quest"); trackLearningEvent("learning_game_start", { game: "fact-check-quest" }); };
  const current = factQuestions[index];
  const orderedChoices = orderChoices(current.choices, `fact-check-${index}`);
  const choose = (id: string) => { if (selected) return; setSelected(id); const choice = current.choices.find((item) => item.id === id); trackLearningEvent("learning_game_answer", { game: "fact-check-quest", question: index + 1, correct: Boolean(choice?.correct) }); if (current.choices.find((choice) => choice.id === id)?.correct) { setScore((value) => value + 1); toast.success("Good investigation. Read the evidence note."); } };
  const next = () => { if (!selected) return; if (index === factQuestions.length - 1) { const finalScore = score; completeGame("fact-check-quest", finalScore); trackLearningEvent("learning_game_complete", { game: "fact-check-quest", score: finalScore, total: factQuestions.length }); if (finalScore > best) { setBest(finalScore); window.localStorage.setItem(STORAGE_KEY, String(finalScore)); } setIndex(factQuestions.length); return; } setIndex((value) => value + 1); setSelected(null); };
  const restart = () => { trackLearningEvent("learning_game_exit", { game: "fact-check-quest", question: index + 1 }); setStarted(false); setIndex(0); setScore(0); setSelected(null); };
  if (!started) return <div className="game-picker"><button className="game-back game-hub-back" onClick={() => { window.location.href = "/play" }}><ArrowLeft size={15} /> Learning games</button><div className="game-picker-heading"><span className="game-kicker">FACT CHECK QUEST / FIELD GAME 02</span><h2>Follow the<br /><em>evidence trail.</em></h2><p>Thirty evidence cases that turn “sounds true” into a better verification habit.</p></div><div className="fact-preview"><span className="fact-preview-icon"><SearchCheck size={24} /></span><div><strong>What you will practice</strong><p>Question absolute claims, inspect source quality and verify original evidence.</p></div></div><button className="game-button game-button--primary fact-start" onClick={start}>Open the first case <ArrowRight size={16} /></button>{best > 0 && <div className="best-score"><Sparkles size={15} /> Best evidence score: <strong>{best}/{factQuestions.length}</strong></div>}</div>;
  if (index >= factQuestions.length) return <div className="game-result"><div className="result-mark badge-burst"><SearchCheck size={26} /></div><span className="game-kicker">EVIDENCE TRAIL COMPLETE</span><h2>{score}<small> / {factQuestions.length}</small></h2><p className="result-message">{score >= 3 ? "You are asking the questions that make information safer to use." : "The habit grows with practice: pause, inspect, verify."}</p><div className="result-note"><strong>Your next move</strong><span>Before sharing an AI answer, find the original source and write down what you checked.</span></div><PostGameFeedback game="fact-check-quest" /><ShareResult game="fact-check-quest" score={score} total={factQuestions.length} /><div className="game-result-actions"><button className="game-button game-button--primary" onClick={() => { setIndex(0); setScore(0); setSelected(null); }}><RotateCcw size={16} /> Play again</button><button className="game-button game-button--quiet" onClick={restart}>Choose another game</button><a className="game-button game-button--quiet" href={`/certificate?game=fact-check-quest&score=${score}&total=${factQuestions.length}`}>Share certificate <ArrowRight size={15} /></a></div></div>;
  const chosen = current.choices.find((choice) => choice.id === selected);
  return <div className="game-play"><div className="game-progress-row"><span>CASE {String(index + 1).padStart(2, "0")} / {String(factQuestions.length).padStart(2, "0")}</span><span>{score} verified</span></div><div className="game-progress"><span style={{ width: `${((index + (selected ? 1 : 0)) / factQuestions.length) * 100}%` }} /></div><div className="fact-claim"><span className="game-kicker">EVIDENCE CARD / CHECK THE CLAIM</span><blockquote>{current.claim}</blockquote><p>{current.context}</p></div><div className="answer-list">{orderedChoices.map((choice, choiceIndex) => <button key={choice.id} className={`answer-card ${selected === choice.id ? "is-selected" : ""} ${selected && choice.correct ? "is-correct" : ""} ${selected === choice.id && !choice.correct ? "is-wrong" : ""}`} disabled={Boolean(selected)} onClick={() => choose(choice.id)}><span className="answer-letter">{String.fromCharCode(65 + choiceIndex)}</span><span>{choice.text}</span>{selected && choice.correct && <Check className="answer-status" size={17} />}{selected === choice.id && !choice.correct && <X className="answer-status" size={17} />}</button>)}</div>{selected && <div className={`game-feedback ${chosen?.correct ? "game-feedback--good" : "game-feedback--learn"}`}><div className="feedback-icon">{chosen?.correct ? <Check size={17} /> : <Sparkles size={17} />}</div><div><strong>{chosen?.correct ? "The evidence trail checks out." : "Pause and inspect the source."}</strong><p>{chosen?.explanation}</p></div></div>}<div className="game-footer-actions"><a className="game-back" href="/play"><ArrowLeft size={15} /> Prompt Detective</a><button className="game-button game-button--primary" onClick={next} disabled={!selected}>{index === factQuestions.length - 1 ? "See your result" : "Next case"} <ArrowRight size={16} /></button></div></div>;
}
