import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, RotateCcw, Search, Sparkles } from "lucide-react";
import { reviewedMeta } from "@/data/contentSchema";
import { completeGame, startGame, GameId } from "@/lib/learningProgress";
import { trackLearningEvent } from "@/lib/analytics";
import ShareResult from "@/components/game/ShareResult";

type Mode = "workshop" | "source-hunt";
type Challenge = { title: string; brief: string; blocks: string[]; correct: string[]; lesson: string; learningObjective?: string; reviewStatus?: string };

const challengeBank: Record<Mode, Challenge[]> = {
  workshop: [
    { title: "Build a study prompt", brief: "Assemble the blocks that turn a broad topic into a useful learning request.", blocks: ["Ask for a beginner explanation", "Name the topic: photosynthesis", "Request an analogy and three questions", "Hide the goal"], correct: ["Name the topic: photosynthesis", "Ask for a beginner explanation", "Request an analogy and three questions"], lesson: "A strong prompt names the task, audience and useful output." },
    { title: "Design a feedback loop", brief: "Create a prompt that helps you improve an essay without outsourcing your voice.", blocks: ["Ask for two revision priorities", "Share the marking criteria", "Request a full replacement essay", "Ask questions before edits"], correct: ["Share the marking criteria", "Ask for two revision priorities", "Ask questions before edits"], lesson: "Criteria and questions make AI feedback more useful than a silent rewrite." },
    { title: "Set a safe boundary", brief: "Choose the parts of a prompt that keep a research answer checkable.", blocks: ["Ask it to label uncertainty", "Request source leads", "Tell it to invent missing facts", "Ask for the evidence behind each claim"], correct: ["Request source leads", "Ask it to label uncertainty", "Ask for the evidence behind each claim"], lesson: "A visible evidence trail keeps the learner in charge of the conclusion." },
    { title: "Name the learner", brief: "Build a prompt that changes explanation level without changing the topic.", blocks: ["Say what you already know", "Ask for graduate-level jargon", "Name your current level", "Request one analogy"], correct: ["Name your current level", "Say what you already know", "Request one analogy"], lesson: "Audience and prior knowledge make explanations more useful." },
    { title: "Make practice active", brief: "Create a study request that gives you a way to test understanding.", blocks: ["Ask for five retrieval questions", "Request only a polished paragraph", "Specify no answers until you try", "Name the chapter"], correct: ["Name the chapter", "Ask for five retrieval questions", "Specify no answers until you try"], lesson: "Retrieval practice turns an explanation into learning." },
    { title: "Repair a vague brief", brief: "Turn a broad writing request into a task you can inspect.", blocks: ["Define the audience", "Say ‘make it good’", "Choose the format", "State the purpose"], correct: ["State the purpose", "Define the audience", "Choose the format"], lesson: "Purpose, audience and format make quality visible." },
    { title: "Ask for counterexamples", brief: "Build a prompt that helps you find the edge of a concept.", blocks: ["Name the concept", "Ask for two counterexamples", "Ask it to hide uncertainty", "Request a short explanation"], correct: ["Name the concept", "Request a short explanation", "Ask for two counterexamples"], lesson: "Counterexamples reveal where a rule stops working." },
    { title: "Keep your voice", brief: "Choose a feedback workflow that improves an essay without replacing its author.", blocks: ["Share your rubric", "Ask for questions first", "Request a full rewrite", "Paste your own draft"], correct: ["Paste your own draft", "Share your rubric", "Ask for questions first"], lesson: "Feedback should help you revise your thinking, not erase your authorship." },
    { title: "Plan a revision", brief: "Assemble a prompt that produces an actionable revision plan.", blocks: ["Request three priorities", "Name the deadline", "Ask for every possible edit", "Explain the assignment"], correct: ["Explain the assignment", "Name the deadline", "Request three priorities"], lesson: "A small prioritized plan is easier to act on than a wall of edits." },
    { title: "Compare explanations", brief: "Ask for two explanations you can evaluate rather than one answer to trust.", blocks: ["Ask for two approaches", "Name the learner", "Request a comparison table", "Tell it to pick silently"], correct: ["Name the learner", "Ask for two approaches", "Request a comparison table"], lesson: "Comparison exposes trade-offs and gives you something to check." },
    { title: "Handle uncertainty", brief: "Build a request that makes unknowns visible in a research note.", blocks: ["Ask it to mark unknowns", "Request source leads", "Demand a certain tone", "List your known facts"], correct: ["List your known facts", "Ask it to mark unknowns", "Request source leads"], lesson: "Separating knowns, unknowns and leads prevents false certainty." },
    { title: "Make a study plan", brief: "Create a prompt that turns a deadline into manageable sessions.", blocks: ["State the exam date", "Name available study time", "Ask for daily checkpoints", "Request an impossible syllabus"], correct: ["State the exam date", "Name available study time", "Ask for daily checkpoints"], lesson: "Time and checkpoints turn intention into a plan you can follow." },
    { title: "Ask for a rubric", brief: "Assemble a request that helps you evaluate your own draft.", blocks: ["Name the assignment", "Ask for observable criteria", "Request a score without reasons", "Include the audience"], correct: ["Name the assignment", "Include the audience", "Ask for observable criteria"], lesson: "Observable criteria make self-review concrete." },
    { title: "Close the loop", brief: "Build the final instruction that makes an AI response easy to verify.", blocks: ["Ask it to summarize its assumptions", "Request a confidence label", "Tell it never to ask questions", "Specify the output format"], correct: ["Specify the output format", "Ask it to summarize its assumptions", "Request a confidence label"], lesson: "Format, assumptions and uncertainty create a useful review surface." },
  ],
  "source-hunt": [
    { title: "Trace a claim", brief: "Put the evidence workflow in the order you would use before sharing a claim.", blocks: ["Read the original source", "Notice the claim", "Check author, date and method", "Share immediately"], correct: ["Notice the claim", "Read the original source", "Check author, date and method"], lesson: "Good checking starts by defining the claim and ends with inspecting the source." },
    { title: "Read a chart", brief: "Sequence the checks that prevent a chart from misleading you.", blocks: ["Inspect axes and units", "Ask what comparison is being made", "Look for sample and timeframe", "Trust the visual impression"], correct: ["Ask what comparison is being made", "Inspect axes and units", "Look for sample and timeframe"], lesson: "A chart is evidence only after its scale, sample and timeframe are understood." },
    { title: "Verify a citation", brief: "Build a reliable citation check before it enters your notes.", blocks: ["Find the publisher or library record", "Compare author, title and date", "Check the cited passage supports the claim", "Copy the citation from the chatbot"], correct: ["Find the publisher or library record", "Compare author, title and date", "Check the cited passage supports the claim"], lesson: "A realistic-looking citation still needs an original record and supporting passage." },
    { title: "Check a headline", brief: "Sequence the checks before repeating a dramatic headline.", blocks: ["Find the full article", "Read beyond the headline", "Check date and author", "Share the screenshot"], correct: ["Find the full article", "Read beyond the headline", "Check date and author"], lesson: "Headlines compress context; the article and its date restore it." },
    { title: "Inspect a study", brief: "Build a quick check for a research claim.", blocks: ["Find the original study", "Check sample and method", "Read the stated limitation", "Trust the influencer summary"], correct: ["Find the original study", "Check sample and method", "Read the stated limitation"], lesson: "Method and limitations tell you what a study can actually support." },
    { title: "Track an image", brief: "Sequence a reverse-image check before sharing a picture.", blocks: ["Search for earlier appearances", "Inspect the original context", "Check date and location", "Assume the caption is original"], correct: ["Search for earlier appearances", "Inspect the original context", "Check date and location"], lesson: "Images travel with captions that may not belong to their original context." },
    { title: "Read a percentage", brief: "Build the checks needed to interpret a percentage responsibly.", blocks: ["Find the denominator", "Check the timeframe", "Ask what changed", "Repeat the biggest number"], correct: ["Ask what changed", "Find the denominator", "Check the timeframe"], lesson: "A percentage needs a base and a time window before it can be interpreted." },
    { title: "Compare two sources", brief: "Put two sources into a fair comparison.", blocks: ["Define the same claim", "Compare methods and dates", "Check who funded the work", "Choose the longer article"], correct: ["Define the same claim", "Compare methods and dates", "Check who funded the work"], lesson: "Fair comparison uses the same claim and inspects how each source was made." },
    { title: "Find missing context", brief: "Sequence a context check for a cropped quote.", blocks: ["Locate the full transcript", "Read nearby sentences", "Check who is speaking", "Share the crop as proof"], correct: ["Locate the full transcript", "Read nearby sentences", "Check who is speaking"], lesson: "A quote can change meaning when speaker and surrounding context disappear." },
    { title: "Check a date", brief: "Build a freshness check for a changing claim.", blocks: ["Identify when the claim matters", "Check publication and update dates", "Compare with a current source", "Use the oldest result"], correct: ["Identify when the claim matters", "Check publication and update dates", "Compare with a current source"], lesson: "Time-sensitive claims need current, dated evidence." },
    { title: "Inspect a chart", brief: "Sequence the checks that reveal a misleading chart.", blocks: ["Read title and labels", "Inspect axes and units", "Check the underlying source", "Judge by color alone"], correct: ["Read title and labels", "Inspect axes and units", "Check the underlying source"], lesson: "Labels, scale and provenance turn a visual impression into inspectable evidence." },
    { title: "Test a quote", brief: "Verify whether a famous quote is correctly attributed.", blocks: ["Find a primary record", "Compare exact wording", "Check date and speaker", "Trust the quote card"], correct: ["Find a primary record", "Compare exact wording", "Check date and speaker"], lesson: "Attribution needs a primary record, not just a repeated graphic." },
    { title: "Spot a conflict", brief: "Add a useful conflict-of-interest check to a source review.", blocks: ["Identify the claim", "Look for funding or incentives", "Compare independent sources", "Reject every source automatically"], correct: ["Identify the claim", "Look for funding or incentives", "Compare independent sources"], lesson: "An incentive is a reason to inspect a claim more carefully, not proof by itself." },
    { title: "Write a verdict", brief: "Build a fair conclusion after checking a claim.", blocks: ["State what the evidence supports", "Name what remains uncertain", "Link the strongest source", "Say it is definitely true"], correct: ["State what the evidence supports", "Name what remains uncertain", "Link the strongest source"], lesson: "A calibrated verdict separates support from uncertainty." },
    { title: "Check the denominator", brief: "Make a percentage interpretable before repeating it.", blocks: ["Find the underlying total", "Check which group is counted", "Repeat the percentage alone", "Compare the timeframe"], correct: ["Find the underlying total", "Check which group is counted", "Compare the timeframe"], lesson: "A denominator tells you what a percentage actually describes." },
    { title: "Read inclusion rules", brief: "Find who the evidence includes before applying the finding.", blocks: ["Read inclusion criteria", "Compare participants with the claim", "Ignore exclusions", "Record the scope"], correct: ["Read inclusion criteria", "Compare participants with the claim", "Record the scope"], lesson: "Inclusion rules define who a result represents." },
    { title: "Check a correction", brief: "Find whether an older claim was updated after new evidence.", blocks: ["Look for an update note", "Compare the revised conclusion", "Use the first version only", "Record what changed"], correct: ["Look for an update note", "Compare the revised conclusion", "Record what changed"], lesson: "Corrections and updates are part of a source's evidence trail." },
    { title: "Separate evidence types", brief: "Keep an opinion, observation and experiment from being treated as the same thing.", blocks: ["Label each evidence type", "Check the method", "Call every statement a fact", "Compare what each can support"], correct: ["Label each evidence type", "Check the method", "Compare what each can support"], lesson: "Different evidence types support different strengths of conclusion." },
    { title: "Audit a model answer", brief: "Check an AI-generated research answer before citing it.", blocks: ["List its factual claims", "Open the cited sources", "Accept invented details", "Mark unsupported claims"], correct: ["List its factual claims", "Open the cited sources", "Mark unsupported claims"], lesson: "AI output is a lead to verify, not a source by itself." },
    { title: "Inspect a survey", brief: "Judge whether a survey question could shape the result.", blocks: ["Read the exact wording", "Check response options", "Ignore leading language", "Compare the sampling method"], correct: ["Read the exact wording", "Check response options", "Compare the sampling method"], lesson: "Question wording and sampling can influence what a survey reports." },
    { title: "Compare time windows", brief: "Avoid a misleading comparison made from different periods.", blocks: ["Align the time windows", "Check seasonal effects", "Compare unmatched periods", "Record the dates"], correct: ["Align the time windows", "Check seasonal effects", "Record the dates"], lesson: "Comparable time windows make change easier to interpret." },
    { title: "Check the unit", brief: "Make sure two numbers measure the same thing.", blocks: ["Read the unit", "Confirm the conversion", "Compare labels only", "Check the measurement definition"], correct: ["Read the unit", "Confirm the conversion", "Check the measurement definition"], lesson: "A shared number is meaningless if its units or definitions differ." },
    { title: "Find the limitation", brief: "Locate the sentence that keeps a finding from being overclaimed.", blocks: ["Read the limitations", "Compare them with the headline", "Delete caveats", "State what remains unknown"], correct: ["Read the limitations", "Compare them with the headline", "State what remains unknown"], lesson: "Limitations set the boundary around a conclusion." },
    { title: "Check authorship", brief: "Verify who actually created or reviewed a source.", blocks: ["Find the named author", "Check credentials in context", "Assume an anonymous repost is primary", "Trace the publication record"], correct: ["Find the named author", "Check credentials in context", "Trace the publication record"], lesson: "Authorship and publication records help establish provenance." },
    { title: "Inspect a recommendation", brief: "Understand why a system may be showing one result repeatedly.", blocks: ["Check the ranking basis", "Look for personalization", "Treat repetition as proof", "Compare alternative results"], correct: ["Check the ranking basis", "Look for personalization", "Compare alternative results"], lesson: "Recommendations reflect system choices, not neutral reality." },
    { title: "Verify a policy", brief: "Check whether a rule applies to your current situation.", blocks: ["Find the official policy", "Check its effective date", "Read exceptions", "Use an old summary"], correct: ["Find the official policy", "Check its effective date", "Read exceptions"], lesson: "Policies need current, authoritative text and relevant exceptions." },
    { title: "Build a fair summary", brief: "Summarize evidence without hiding disagreement or uncertainty.", blocks: ["State the main finding", "Include meaningful disagreement", "Label confidence and limits", "Choose only supportive sources"], correct: ["State the main finding", "Include meaningful disagreement", "Label confidence and limits"], lesson: "Fair summaries preserve uncertainty and relevant counterevidence." },
    { title: "Make it reproducible", brief: "Leave enough information for another learner to repeat your check.", blocks: ["Record search terms", "Save source links and dates", "Keep the decision rule", "Delete the working notes"], correct: ["Record search terms", "Save source links and dates", "Keep the decision rule"], lesson: "Reproducibility depends on preserving the path, not only the conclusion." },
  ],
};

const workshopExpansion: Challenge[] = [
  { title: "Set a success test", brief: "Make the output easy to judge before you ask for it.", blocks: ["Name what success looks like", "Choose a review signal", "Hide the audience", "Ask for a random answer"], correct: ["Name what success looks like", "Choose a review signal", "Hide the audience"], lesson: "A visible success test helps you decide whether an output is useful." },
  { title: "Turn notes into recall", brief: "Build a request that turns notes into active practice.", blocks: ["Paste the relevant notes", "Set a difficulty level", "Ask for questions first", "Request the answer immediately"], correct: ["Paste the relevant notes", "Set a difficulty level", "Ask for questions first"], lesson: "Relevant notes, level and delayed answers create a stronger practice loop." },
  { title: "Choose a useful tone", brief: "Create a prompt that makes an explanation clear rather than vague.", blocks: ["Name the learner", "Request plain language", "Specify the emotional tone", "Ask for maximum jargon"], correct: ["Name the learner", "Request plain language", "Specify the emotional tone"], lesson: "Tone works best when connected to audience and comprehension." },
  { title: "Plan an experiment", brief: "Ask AI to help design a small, checkable learning experiment.", blocks: ["State the question", "Define one variable", "Name how you will observe it", "Request a result guarantee"], correct: ["State the question", "Define one variable", "Name how you will observe it"], lesson: "A narrow question and observable measure make experiments teachable." },
  { title: "Make a comparison", brief: "Assemble a fair comparison request for two AI tools.", blocks: ["Use the same task", "Define evaluation criteria", "Record the limitations", "Choose the tool you already like"], correct: ["Use the same task", "Define evaluation criteria", "Record the limitations"], lesson: "Fair comparisons keep the task constant and trade-offs visible." },
  { title: "Improve an explanation", brief: "Find the part of an explanation you do not understand.", blocks: ["Paste the confusing passage", "Name the exact stumbling point", "Ask for a different example", "Request a longer answer only"], correct: ["Paste the confusing passage", "Name the exact stumbling point", "Ask for a different example"], lesson: "Specific confusion plus a new example beats asking for length alone." },
  { title: "Protect your authorship", brief: "Keep the final decision with you while using AI feedback.", blocks: ["Share your draft", "Ask for questions and options", "Choose which suggestion to use", "Request a replacement in your voice"], correct: ["Share your draft", "Ask for questions and options", "Choose which suggestion to use"], lesson: "Human choice and visible options preserve ownership." },
  { title: "Request a source trail", brief: "Make a research answer easier to audit later.", blocks: ["Ask for source leads", "Request the relevant passage", "Record the access date", "Accept uncited claims"], correct: ["Ask for source leads", "Request the relevant passage", "Record the access date"], lesson: "A source trail is useful when the claim can be retraced." },
  { title: "Handle a wrong answer", brief: "Build a prompt for correcting a plausible but unsupported response.", blocks: ["Quote the exact error", "Provide reliable evidence", "Ask what changed", "Hide the correction"], correct: ["Quote the exact error", "Provide reliable evidence", "Ask what changed"], lesson: "Specific correction and reflection turn an error into learning." },
  { title: "Fit the time", brief: "Turn a long task into a realistic AI-supported study session.", blocks: ["State the time available", "Choose the must-learn outcome", "Add a stopping point", "Request every related topic"], correct: ["State the time available", "Choose the must-learn outcome", "Add a stopping point"], lesson: "Time, priority and a stopping point prevent overload." },
  { title: "Ask for alternatives", brief: "Avoid locking onto the first approach.", blocks: ["Describe the goal", "Request two viable approaches", "Ask for trade-offs", "Demand one answer only"], correct: ["Describe the goal", "Request two viable approaches", "Ask for trade-offs"], lesson: "Alternatives and trade-offs make decisions deliberate." },
  { title: "Clarify a constraint", brief: "Make one important boundary impossible to miss.", blocks: ["State the non-negotiable rule", "Give a realistic example", "Ask for a compliance check", "Say ignore the policy"], correct: ["State the non-negotiable rule", "Give a realistic example", "Ask for a compliance check"], lesson: "Constraints should be explicit, illustrated and checked." },
  { title: "Review a draft", brief: "Separate strengths from next actions.", blocks: ["Name what already works", "Ask for two priorities", "Tie feedback to the rubric", "Request every typo at once"], correct: ["Name what already works", "Ask for two priorities", "Tie feedback to the rubric"], lesson: "Balanced, prioritized feedback is easier to apply." },
  { title: "Use a role carefully", brief: "Add perspective without inventing authority.", blocks: ["Name the perspective", "State the task and limits", "Ask it to flag uncertainty", "Claim it is a licensed professional"], correct: ["Name the perspective", "State the task and limits", "Ask it to flag uncertainty"], lesson: "Roles shape perspective but cannot create credentials." },
  { title: "End with reflection", brief: "Build a final step that helps you learn from the output.", blocks: ["Ask what assumption mattered", "Write one thing you will verify", "State what you still do not understand", "Copy the answer without reading"], correct: ["Ask what assumption mattered", "Write one thing you will verify", "State what you still do not understand"], lesson: "Reflection turns an AI response into a learner-owned next step." },
];

const challenges: Record<Mode, Challenge[]> = {
  workshop: [...challengeBank.workshop, ...workshopExpansion].map((item, index) => ({ ...item, ...reviewedMeta("prompt-workshop", index, item.title, ["prompting", "writing"]) })),
  "source-hunt": challengeBank["source-hunt"].map((item, index) => ({ ...item, ...reviewedMeta("source-hunt", index, item.title, ["evidence", "research"]) })),
};

export default function InteractiveLab({ mode }: { mode: Mode }) {
  const gameId: GameId = mode === "workshop" ? "prompt-workshop" : "source-hunt";
  const icon = mode === "workshop" ? <Sparkles size={24} /> : <Search size={24} />;
  const [started, setStarted] = useState(false); const [round, setRound] = useState(0); const [picked, setPicked] = useState<string[]>([]); const [score, setScore] = useState(0); const [done, setDone] = useState(false); const cases = challenges[mode]; const current = cases[round];
  const remaining = useMemo(() => current?.blocks.filter((block) => !picked.includes(block)) || [], [current, picked]);
  const start = () => { setStarted(true); setRound(0); setPicked([]); setScore(0); setDone(false); startGame(gameId); trackLearningEvent("learning_game_start", { game: gameId }); };
  const choose = (block: string) => { if (!picked.includes(block)) setPicked((value) => [...value, block]); };
  const submit = () => { if (picked.length !== current.correct.length) return; const correct = picked.every((value, index) => value === current.correct[index]); if (correct) setScore((value) => value + 1); trackLearningEvent("learning_game_answer", { game: gameId, round: round + 1, correct }); if (round === cases.length - 1) { const finalScore = score + (correct ? 1 : 0); completeGame(gameId, finalScore); trackLearningEvent("learning_game_complete", { game: gameId, score: finalScore, total: cases.length }); setDone(true); } else { setRound((value) => value + 1); setPicked([]); } };
  if (!started) return <div className="game-picker"><a className="game-back game-hub-back" href="/play"><ArrowLeft size={15} /> Learning games</a><div className="game-picker-heading"><span className="game-kicker">{mode === "workshop" ? "PROMPT WORKSHOP / HANDS-ON LAB" : "SOURCE HUNT / HANDS-ON LAB"}</span><h2>{mode === "workshop" ? <>Build the<br /><em>better brief.</em></> : <>Follow the<br /><em>evidence trail.</em></>}</h2><p>{mode === "workshop" ? "Assemble useful prompt blocks instead of choosing a right answer." : "Sequence the checks that make an AI claim safer to share."}</p></div><div className="fact-preview"><span className="fact-preview-icon">{icon}</span><div><strong>Interactive practice</strong><p>Choose blocks, see the result and learn the principle behind the move.</p></div></div><button className="game-button game-button--primary fact-start" onClick={start}>Start the lab <ArrowRight size={16} /></button></div>;
  if (done) return <div className="game-result"><div className="result-mark badge-burst">{icon}</div><span className="game-kicker">LAB COMPLETE</span><h2>{score}<small> / {cases.length}</small></h2><p className="result-message">You learned by building the workflow, not by memorizing a label.</p><ShareResult game={gameId} score={score} total={cases.length} /><div className="game-result-actions"><button className="game-button game-button--primary" onClick={start}><RotateCcw size={16} /> Run it again</button><a className="game-button game-button--quiet" href="/play">Choose another game</a></div></div>;
  return <div className="game-play"><div className="game-progress-row"><span>CHALLENGE {round + 1} / {cases.length}</span><span>{score} solved</span></div><div className="game-progress"><span style={{ width: `${((round + (picked.length ? .5 : 0)) / cases.length) * 100}%` }} /></div><div className="fact-claim"><span className="game-kicker">{mode === "workshop" ? "WORKBENCH / ASSEMBLE" : "FIELD NOTE / SEQUENCE"}</span><blockquote>{current.title}</blockquote><p>{current.brief}</p></div><div className="interactive-order">{picked.map((block, index) => <button className="order-block is-picked" key={block} onClick={() => setPicked((value) => value.filter((item) => item !== block))}><span>{index + 1}</span>{block}</button>)}{remaining.map((block) => <button className="order-block" key={block} onClick={() => choose(block)}><span>+</span>{block}</button>)}</div><div className="interactive-note"><strong>Build the sequence</strong><span>Tap blocks in the order that makes the workflow safer and more useful. Tap a chosen block to remove it.</span></div><div className="game-footer-actions"><a className="game-back" href="/play"><ArrowLeft size={15} /> Exit lab</a><button className="game-button game-button--primary" onClick={submit} disabled={picked.length !== current.correct.length}>Check the build <Check size={16} /></button></div></div>;
}
