import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, RotateCcw, Search, Sparkles } from "lucide-react";
import { completeGame, startGame, GameId } from "@/lib/learningProgress";
import { trackLearningEvent } from "@/lib/analytics";
import ShareResult from "@/components/game/ShareResult";

type Mode = "workshop" | "source-hunt";
type Challenge = { title: string; brief: string; blocks: string[]; correct: string[]; lesson: string };

const challenges: Record<Mode, Challenge[]> = {
  workshop: [
    { title: "Build a study prompt", brief: "Assemble the blocks that turn a broad topic into a useful learning request.", blocks: ["Ask for a beginner explanation", "Name the topic: photosynthesis", "Request an analogy and three questions", "Hide the goal"], correct: ["Name the topic: photosynthesis", "Ask for a beginner explanation", "Request an analogy and three questions"], lesson: "A strong prompt names the task, audience and useful output." },
    { title: "Design a feedback loop", brief: "Create a prompt that helps you improve an essay without outsourcing your voice.", blocks: ["Ask for two revision priorities", "Share the marking criteria", "Request a full replacement essay", "Ask questions before edits"], correct: ["Share the marking criteria", "Ask for two revision priorities", "Ask questions before edits"], lesson: "Criteria and questions make AI feedback more useful than a silent rewrite." },
    { title: "Set a safe boundary", brief: "Choose the parts of a prompt that keep a research answer checkable.", blocks: ["Ask it to label uncertainty", "Request source leads", "Tell it to invent missing facts", "Ask for the evidence behind each claim"], correct: ["Request source leads", "Ask it to label uncertainty", "Ask for the evidence behind each claim"], lesson: "A visible evidence trail keeps the learner in charge of the conclusion." },
  ],
  "source-hunt": [
    { title: "Trace a claim", brief: "Put the evidence workflow in the order you would use before sharing a claim.", blocks: ["Read the original source", "Notice the claim", "Check author, date and method", "Share immediately"], correct: ["Notice the claim", "Read the original source", "Check author, date and method"], lesson: "Good checking starts by defining the claim and ends with inspecting the source." },
    { title: "Read a chart", brief: "Sequence the checks that prevent a chart from misleading you.", blocks: ["Inspect axes and units", "Ask what comparison is being made", "Look for sample and timeframe", "Trust the visual impression"], correct: ["Ask what comparison is being made", "Inspect axes and units", "Look for sample and timeframe"], lesson: "A chart is evidence only after its scale, sample and timeframe are understood." },
    { title: "Verify a citation", brief: "Build a reliable citation check before it enters your notes.", blocks: ["Find the publisher or library record", "Compare author, title and date", "Check the cited passage supports the claim", "Copy the citation from the chatbot"], correct: ["Find the publisher or library record", "Compare author, title and date", "Check the cited passage supports the claim"], lesson: "A realistic-looking citation still needs an original record and supporting passage." },
  ],
};

export default function InteractiveLab({ mode }: { mode: Mode }) {
  const gameId: GameId = mode === "workshop" ? "prompt-workshop" : "source-hunt";
  const icon = mode === "workshop" ? <Sparkles size={24} /> : <Search size={24} />;
  const [started, setStarted] = useState(false); const [round, setRound] = useState(0); const [picked, setPicked] = useState<string[]>([]); const [score, setScore] = useState(0); const [done, setDone] = useState(false); const cases = challenges[mode]; const current = cases[round];
  const remaining = useMemo(() => current?.blocks.filter((block) => !picked.includes(block)) || [], [current, picked]);
  const start = () => { setStarted(true); setRound(0); setPicked([]); setScore(0); setDone(false); startGame(gameId); trackLearningEvent("learning_game_start", { game: gameId }); };
  const choose = (block: string) => { if (!picked.includes(block)) setPicked((value) => [...value, block]); };
  const submit = () => { if (picked.length !== current.correct.length) return; const correct = picked.every((value, index) => value === current.correct[index]); if (correct) setScore((value) => value + 1); trackLearningEvent("learning_game_answer", { game: gameId, round: round + 1, correct }); if (round === cases.length - 1) { const finalScore = score + (correct ? 1 : 0); completeGame(gameId, finalScore); trackLearningEvent("learning_game_complete", { game: gameId, score: finalScore, total: cases.length }); setDone(true); } else { setRound((value) => value + 1); setPicked([]); } };
  if (!started) return <div className="game-picker"><a className="game-back game-hub-back" href="/play"><ArrowLeft size={15} /> Learning games</a><div className="game-picker-heading"><span className="game-kicker">{mode === "workshop" ? "PROMPT WORKSHOP / HANDS-ON LAB" : "SOURCE HUNT / HANDS-ON LAB"}</span><h2>{mode === "workshop" ? <>Build the<br /><em>better brief.</em></> : <>Follow the<br /><em>evidence trail.</em></>}</h2><p>{mode === "workshop" ? "Assemble useful prompt blocks instead of choosing a right answer." : "Sequence the checks that make an AI claim safer to share."}</p></div><div className="fact-preview"><span className="fact-preview-icon">{icon}</span><div><strong>Interactive practice</strong><p>Choose blocks, see the result and learn the principle behind the move.</p></div></div><button className="game-button game-button--primary fact-start" onClick={start}>Start the lab <ArrowRight size={16} /></button></div>;
  if (done) return <div className="game-result"><div className="result-mark badge-burst">{icon}</div><span className="game-kicker">LAB COMPLETE</span><h2>{score}<small> / {cases.length}</small></h2><p className="result-message">You learned by building the workflow, not by memorizing a label.</p><ShareResult game={gameId} score={score} total={cases.length} /><div className="game-result-actions"><button className="game-button game-button--primary" onClick={start}><RotateCcw size={16} /> Run it again</button><a className="game-button game-button--quiet" href="/play">Choose another game</a></div></div>;
  return <div className="game-play"><div className="game-progress-row"><span>CHALLENGE {round + 1} / {cases.length}</span><span>{score} solved</span></div><div className="game-progress"><span style={{ width: `${((round + (picked.length ? .5 : 0)) / cases.length) * 100}%` }} /></div><div className="fact-claim"><span className="game-kicker">{mode === "workshop" ? "WORKBENCH / ASSEMBLE" : "FIELD NOTE / SEQUENCE"}</span><blockquote>{current.title}</blockquote><p>{current.brief}</p></div><div className="interactive-order">{picked.map((block, index) => <button className="order-block is-picked" key={block} onClick={() => setPicked((value) => value.filter((item) => item !== block))}><span>{index + 1}</span>{block}</button>)}{remaining.map((block) => <button className="order-block" key={block} onClick={() => choose(block)}><span>+</span>{block}</button>)}</div><div className="interactive-note"><strong>Build the sequence</strong><span>Tap blocks in the order that makes the workflow safer and more useful. Tap a chosen block to remove it.</span></div><div className="game-footer-actions"><a className="game-back" href="/play"><ArrowLeft size={15} /> Exit lab</a><button className="game-button game-button--primary" onClick={submit} disabled={picked.length !== current.correct.length}>Check the build <Check size={16} /></button></div></div>;
}
